export enum ROUTING {
    HOME = '/',
    DASHBOARD = 'dashboard',
    PURCHASE_AGREEMENT = 'purchase-agreement',
    SALES_AGREEMENT = 'sales-agreement',
    VEHICLE_MASTER = 'vehicle-master',
    HP_APPLICATION = 'hp-application',
    FLOOR_STOCK_APPLICATION = 'floor-stock-application',
    INSURANCE_QUOTATION = 'insurance-quotation',
    CONTACT = 'contact',
    CHAT = 'chat',
    VERIFY_MY_INFO_EMAIL_CODE = 'verify-myinfo-email-code',
    RETRIEVE_MY_INFO_LANDING = 'retrieve-myinfo-landing',
    CALLBACK = 'callback',
    MY_INFO_DETAILS = 'myinfo-details',
    COMPLETED_MY_INFO = 'completed-my-info',
    MANUAL_INPUT_INFO = 'manual-input-info',
  }